"""
Rollercoaster Tycoon utility functions
"""
import random

RIDES = [
    'Steam Trains',
    'Small Monorail Cars',
    'Streamlined Monorail Trains',
    'Chairlift Cars',
    'Steam Trains with Covered Cars',
    'Suspended Monorail',
    'Ski-lift Chairs',
    'American Style Steam Trains',
    'Elevator',
    'Trams',
    'Retro-style Monorail Trains',
    'Mine Lift',
    'London Bus Tram',
    'Maharaja Steam Train',
    'San Francisco Tram',
    'Teleporter',
    'School Bus Ride',
    'Airship Themed Monorail',
    'Haunted House',
    'Ferris Wheel',
    'Maze',
    'Merry-Go-Round',
    'Observation Tower',
    'Sportcars',
    'Racing Cars',
    'Pickup Trucks',
    'Cheshire Cats',
    'Spiral Slide',
    'Dodgems',
    'Space Rings',
    'Monorail Cycles',
    'Crooked House',
    'Mini Golf',
    'Vintage Cars',
    'Mini Helicopters',
    'Circus',
    'Ghost Train',
    'Flying Saucers',
    'Monster Trucks',
    'Double-deck Observation Tower',
    'Haunted Mansion Ride',
    'Huskie Car',
    'London Taxi Black Cab Ride',
    'Chinese Dragonhead Ride',
    'Skidoo Dodgems',
    'Fighting Knights Dodgem Cars',
    'Triceratops Dodgem Cars',
    'Hover Car Ride',
    'Pegasus Ride',
    'Double Deck Carousel',
    'Fun House',
    'Hall of Mirrors',
    'Haunted Jail House',
    'Cyclops Ride',
    'Flower Power Ride',
    'Blob from Outer Space Ride',
    'Mace Ride',
    'Time Machine',
    'Wooden Roller Coaster',
    'Wooden Wild Mine Ride',
    'Wooden Wild Mouse',
    'Ladybird Trains',
    'Log Trains',
    'Rocket Cars',
    'Mine Train Coaster',
    'Looping Roller Coaster',
    'Stand-up Roller Coaster',
    'Corkscrew Roller Coaster',
    'Suspended Swinging Cars',
    'Suspended Swinging Airplane Cars',
    'Swinging Cars',
    'Mini Suspended Flying Coaster',
    'Steeplechase',
    'Motorbike Races',
    'Bobsleigh Coaster',
    'Reverse Freefall Coaster',
    'Vertical Drop Roller Coaster',
    'Side-Friction Roller Coaster',
    'Virginia Reel',
    'Reverser Roller Coaster',
    'Mouse Cars',
    'Twister Roller Coaster',
    'Stand-up Twister Coaster',
    'Floorless Roller Coaster',
    'Heartline Twister Coaster',
    'Heartline Twister Coaster (starting reversed)',
    'Flying Roller Coaster',
    'Inverted Hairpin Coaster',
    'Hypercoaster',
    'Inverted Roller Coaster',
    'Compact Inverted Coaster',
    'Inverted Shuttle Coaster',
    'Air Powered Vertical Coaster',
    'Water Coaster',
    'Flying Turns',
    'Inverted Vertical Shuttle',
    'Giga Coaster',
    'Inverted Impulse Coaster',
    'LIM Launched Roller Coaster',
    'Lay-down Roller Coaster',
    'Mine Ride',
    'Mine Cars',
    'Automobile Cars',
    'Toboggan Cars',
    'Multi-Dimension Roller Coaster',
    'Spiral Roller Coaster',
    'Steel Twister Roller Coaster',
    'Steel Twister Roller Coaster (wide cars)',
    'Soap Box Derby Racers',
    'Swinging Floorless Cars',
    'Spinning Wild Mouse',
    'Articulated Roller Coaster',
    'Boomerang Coaster',
    'Penguin Bobsleigh',
    'Polar Bear Rollercoaster',
    'Anaconda Ride',
    'Bullet Coaster',
    'Conga Eel Coaster',
    'Dragon Coaster',
    'Great White Shark Ride',
    'Limousine Rollercoaster',
    'Seals Rollercoaster',
    'Condor Ride',
    'Yellow Taxi Coaster',
    'Bengal Tiger Rollercoaster',
    'Witchity Grub Ride',
    'TGV Train Roller Coaster',
    'Jaguar Ride',
    'Lion Ride',
    'Russian Cars',
    'Sputnik Suspended Flying Coaster',
    'Koala Ride',
    'Rhino Ride',
    'Ostrich Ride',
    '1950s Rocket Ride',
    'Football Ride',
    'Gorilla Ride',
    'Sloth Ride',
    'Surfing Coaster',
    'Manta Ray Ride',
    'Mine Cart Ride',
    'Stage Coach Rollercoaster',
    'Hot Rod Coaster',
    'Black Death Ride',
    'Pterodactyl Coaster',
    'BarnStorming Coaster',
    'Gangster Car Coaster',
    'Harpies Coaster',
    'Police Chase Coaster',
    'Jet Plane Coaster',
    'Dragonfly Coaster',
    'Hoverboard Coaster',
    'Jet Pack Booster',
    'Police Car Coaster',
    'Battering Ram Coaster',
    'Stampeding Herd Coaster',
    'Cerberus Coaster',
    'Hover Bike Ride',
    'Jousting Knights Coaster',
    'Raptor Racers Coaster',
    'Seaplane Ride',
    'Valkyries Coaster',
    'Flying Boat Ride',
    'Trilobite Boats',
    'Twist',
    'Launched Freefall',
    'Pirate Ship',
    'Go Karts',
    'Swinging Inverter Ship',
    'Motion Simulator',
    '3D Cinema',
    'Top Spin',
    'Roto-Drop',
    'Enterprise',
    'Magic Carpet',
    'Snow Cups',
    'Fire Cracker Ride',
    'Chinese Junk Swing Ride',
    'Coffee Cup Ride',
    'Diamond Ride',
    'Faberge Egg Ride',
    'Fighting Kite Ride',
    'Italian Police Ride',
    'Skidoo Dodgems',
    '1920s Racing Cars',
    'Caveman Cars',
    'MicroBus Ride',
    'Trebuchet Ride',
    'B-Movie Giant Spider Ride',
    'Dinosaur Egg Ride',
    'Neptune Ride',
    'Tommy Gun Ride',
    'Dinghy Slide',
    'Log Flume',
    'River Rapids',
    'Rowing Boats',
    'Swans',
    'Canoes',
    'Bumper Boats',
    'Water Tricycles',
    'Splash Boats',
    'Jet Skis',
    'River Rafts',
    'Submarine Ride',
    'Dhow water ride',
    'Dolphin Ride',
    'Mandarin Duck Water Ride',
    'Outrigger Ride',
    'Turtle Water Ride',
    'Crocodile Ride',
    'Hippo Ride',
    'Killer Whale',
    'River Styx',
    'Oak Barrel Ride',
]

VERSION = [
    '',
    '1',
    '2',
    '3',
]

STATUS = 'has broken down.'


def random_ride():
    return random.choice(RIDES)


def random_version():
    return random.choice(VERSION)
